=== OpaStefanVogel/FORTY-FORTH/R00.dtd
<!ELEMENT los ANY>
<!ELEMENT a ANY>
<!ELEMENT table ANY>
<!ELEMENT code ANY>
<!ELEMENT i ANY>
<!ELEMENT tr ANY>
<!ELEMENT td ANY>
<!ELEMENT step ANY>
<!ELEMENT weiter ANY>
<!ELEMENT favicon ANY>
<!ELEMENT DEMO ANY>
<!ELEMENT u ANY>
<!ELEMENT diff ANY>
<!ELEMENT pr ANY>
<!ELEMENT p ANY>
<!ELEMENT div ANY>
<!ELEMENT ptable ANY>
<!ELEMENT Terminal_1 ANY>
<!ELEMENT Tcl_Console ANY>
<!ELEMENT Terminal_2 ANY>
<!ELEMENT Terminal_3 ANY>
<!ELEMENT li ANY>

=== OpaStefanVogel/FORTY-FORTH/R05_Unterprogramm.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="R00.xsl" ?>
<!DOCTYPE los SYSTEM "R00.dtd">
<los>

<step>Step 5</step>

<pr>Unterprogramm

Zusätzlich zum Sprung an die neue Fortsetzungsadresse muss die normale Fortsetzungsadresse PC+1 in einem Rückkehrstapel zwischengespeichert und bei Rückkehr aus dem Unterprogramm wieder hergestellt werden. 

neue Variablen:
stapR = Array zum Speichern der Rückkehradresse (Rückkehrstapel)
RP    = aktuelle Speicheradresse in stapR 
RPC   = schreibt PC in stapR(RP) hinein, wenn RW='1' ist
RPCC  = liest PC aus stapR(RP) aus 
RW    = "write enable" für stapR

<i>Ausgabe aller ungeraden Zahlen 1, 3, 5, 7..., das Weiterzählen und die Ausgabe sollen in einem extra Unterprogramm erfolgen.</i></pr>

<table border="1"><tr>
<th>PC</th>
<th>PD</th>
<th>FORTH-Notation</th>
<th>Stapelinhalt</th>
<th>SP</th></tr>
  <tr><td> 0000 </td><td> 0001 </td><td> 1                 </td><td> 1   </td><td>1</td></tr>
  <tr><td> 0001 </td><td> 4003 </td><td> BEGIN 0003 EXECUTE</td><td> 1   </td><td>1</td></tr>
  <tr><td> 0002 </td><td> 8FFE </td><td> AGAIN             </td><td> 3   </td><td>1</td></tr>
  <tr><td> 0003 </td><td> 0002 </td><td> 2                 </td><td> 1 2 </td><td>2</td></tr>
  <tr><td> 0004 </td><td> A007 </td><td> +                 </td><td> 3   </td><td>1</td></tr>
  <tr><td> 0005 </td><td> B501 </td><td> DUP               </td><td> 3 3 </td><td>2</td></tr>
  <tr><td> 0006 </td><td> 2D04 </td><td> 2D04              </td><td> 3 3 2D04</td><td>3</td></tr>
  <tr><td> 0007 </td><td> A009 </td><td> !                 </td><td> 3   </td><td>1</td></tr>
  <tr><td> 0008 </td><td> A003 </td><td> ; ( RETURN )      </td><td> 3   </td><td>1</td></tr>
  </table>

<pr>Das Unterprogramm geht von PC=0003 bis PC=0008. Es wird in der Programmschleife PC=0001 bis PC=0002 wiederholt aufgerufen.</pr>

<term>git checkout Step_5
git diff <diff>Step_4...Step_5</diff></term>

<tterm>close_sim -force -quiet
launch_simulation
run 1000 ns</tterm>

<pr><favicon/> Ergebnis: 
ab Zeitpunkt in ns     Wert von LEDS
     0                  UU
   110                  01
   270                  03
   430                  05
   590                  07
   750                  09
   910                  0B
  </pr>

<weiter /><a href="R06_Umstapeln.xml">R06 Umstapeln</a>.

</los>

=== OpaStefanVogel/FORTY-FORTH/R06_Umstapeln.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="R00.xsl" ?>
<!DOCTYPE los SYSTEM "R00.dtd">
<los>

<step>Step 6</step>

<pr>Umstapeln

Übliche FORTH-Worte zum Umstapeln sind

<Maschinencode>PD     FORTH-Wort  Stapeldiagramm
B412    SWAP          ( a b --> b a )
B502    OVER          ( a b --> a b a )
B501    DUP           ( a --> a a )
B434    ROT           ( a b c --> b c a )
B300    DROP          ( a --> )
B43C    2SWAP         ( a b c d --> c d a b )
B60C    2OVER         ( a b c d --> a b c d a b )
B603    2DUP          ( a b --> a b a b )
B200    2DROP         ( a b --> )</Maschinencode>

2ROT habe ich weggelassen, weil dafür mehr als vier obere Stapeleinträge verarbeitet werden. Anstelle nun jedes einzelne FORTH-Wort extra zu programmieren, habe ich versucht, das Umstapeln mit in PD zu codieren, siehe oben Tabellenspalte PD sowie <code>git diff</code>. So hat man mit nur einer Programmfunktion auch noch weitere Umstapelmöglichkeiten, zum Beispiel 

B6A9   für          ( a b c d --> a b a c a d ). 

Hier ein Beispielprogramm, <i>auf den Stapel 4, 3, 2, 1 der Reihe nach alle Worte zum Umstapeln anwenden.</i></pr>
<ptable>
  <tr><td> 0000 </td><td> 0004 </td><td> 4         </td><td> 4          </td><td>1</td></tr>
  <tr><td> 0001 </td><td> 0003 </td><td> 3         </td><td> 4 3        </td><td>2</td></tr>
  <tr><td> 0002 </td><td> 0002 </td><td> 2         </td><td> 4 3 2      </td><td>3</td></tr>
  <tr><td> 0003 </td><td> 0001 </td><td> 1         </td><td> 4 3 2 1    </td><td>4</td></tr>
  <tr><td> 0004 </td><td> B412 </td><td> BEGIN SWAP</td><td> 4 3 1 2    </td><td>4</td></tr>
  <tr><td> 0005 </td><td> B502 </td><td> OVER      </td><td> 4 3 1 2 1  </td><td>5</td></tr>
  <tr><td> 0006 </td><td> B501 </td><td> DUP       </td><td> 4 3 1 2 1 1</td><td>6</td></tr>
  <tr><td> 0007 </td><td> B200 </td><td> 2DROP     </td><td> 4 3 1 2    </td><td>4</td></tr>
  <tr><td> 0008 </td><td> B434 </td><td> ROT       </td><td> 4 1 2 3    </td><td>4</td></tr>
  <tr><td> 0009 </td><td> B43C </td><td> 2SWAP     </td><td> 2 3 4 1    </td><td>4</td></tr>
  <tr><td> 000A </td><td> B60C </td><td> 2OVER     </td><td> 2 3 4 1 2 3</td><td>6</td></tr>
  <tr><td> 000B </td><td> B603 </td><td> 2DUP      </td><td> 2 3 4 1 2 3 2 3</td><td>8</td></tr>
  <tr><td> 000C </td><td> B200 </td><td> 2DROP     </td><td> 2 3 4 1 2 3</td><td>6</td></tr>
  <tr><td> 000D </td><td> B300 </td><td> DROP      </td><td> 2 3 4 1 2  </td><td>5</td></tr>
  <tr><td> 000E </td><td> B300 </td><td> DROP      </td><td> 2 3 4 1    </td><td>4</td></tr>
  <tr><td> 000F </td><td> 8FF4 </td><td> AGAIN     </td><td> 2 3 4 1    </td><td>4</td></tr>
  </ptable>

<p>Da dieses Programm keine extra Ausgabe enthält, ist ausnahmsweise der Ausgabeport LEDS direkt mit der Ausgabe des obersten Stapeleintrages A_SIM verknüpft.</p>

<Terminal_1>
  <li> git checkout Step_6 </li>
  <li> git diff <diff>Step_5...Step_6</diff> </li>
  </Terminal_1>

<Tcl_Console>
  <li> close_sim -force -quiet </li>
  <li> launch_simulation </li>
  <li> run 340 ns </li>
  </Tcl_Console>

<pr><favicon/> Ergebnis: 
ab Zeitpunkt in ns     Wert von D,  C,  B,  A=LEDS
     0                          U   U   U   U
    20                          0   0   0   0
    40                          0   0   0   4
    60                          0   0   4   3
    80                          0   4   3   2
   100                          4   3   2   1
   120                          4   3   1   2
   140                          3   1   2   1
   160                          1   2   1   1
   180                          4   3   1   2
   200                          4   1   2   3
   220                          2   3   4   1
   240                          4   1   2   3
   260                          2   3   2   3
   280                          4   1   2   3
   300                          3   4   1   2
   320                          2   3   4   1
  </pr>

<weiter /><a href="R07_weitere_Rechenoperationen.xml">R07 weitere Rechenoperationen</a>.

<svg_path schnips="0 1 0 100"/>
</los>

=== OpaStefanVogel/FORTY-FORTH/R01_Anfang.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="R00.xsl" ?>
<!DOCTYPE los SYSTEM "R00.dtd">
<los>

<step>Step 1</step>

<pr>Als Anfang ein sehr einfaches Programm.

<i>Der oberste Stapeleintrag soll beginnend mit 0 fortlaufend um 1 erhöht und auf Adresse 2D04 ausgegeben werden.</i>

PC = Speicheradresse des Programmschrittes
PD = Programmcode, gespeichert auf Adresse PC
SP = Stapelhöhe nach Ausführung des Programmschrittes</pr>

<ptable>
  <tr><td> 0000 </td><td> 0000 </td><td> 0       </td><td> 0     </td><td>1</td></tr>
  <tr><td> 0001 </td><td> 0001 </td><td> BEGIN 1 </td><td> 0 1   </td><td>2</td></tr>
  <tr><td> 0002 </td><td> A007 </td><td> +       </td><td> 1     </td><td>1</td></tr>
  <tr><td> 0003 </td><td> B501 </td><td> DUP     </td><td> 1 1   </td><td>2</td></tr>
  <tr><td> 0004 </td><td> 2D04 </td><td> 2D04    </td><td> 1 1 2D04 </td><td>3</td></tr>
  <tr><td> 0005 </td><td> A009 </td><td> !       </td><td> 1     </td><td>1</td></tr>
  <tr><td> 0006 </td><td> 8FFA </td><td> AGAIN   </td><td> 1     </td><td>1</td></tr>
</ptable>

<p>Wer sich noch nicht so sehr mit FORTH auskennt: Anfangs werden "0" und "1" als Zahlen auf den Stapel abgelegt, dann mit "+" addiert, mit "DUP" das Ergebnis dupliziert und "!" speichert das Duplizierte auf der zuvor eingegebenen Adresse "2D04". "AGAIN" springt zurück zu "BEGIN". "BEGIN" ist nur eine Markierung und benötigt selbst keinen eigenen Programmcode.</p>

<p>Genug der Worte, das Programm soll endlich loslaufen. Im Startterminal die Programmversion auswählen:</p>

<Terminal_1>
  <li> git checkout Step_1 </li>
  <li> git diff <diff>Step_0...Step_1</diff> # mit Taste Q beenden </li>
  </Terminal_1>

anschließend in Vivado die Simulation starten:

<Tcl_Console>
  <li> close_sim -force -quiet </li>
  <li> launch_simulation # auch Button "Run Behavioral Simulation" geht </li>
  <li> run 1000 ns </li>
  </Tcl_Console>

<pr><favicon/> Ergebnis: Die Variable LEDS enthält den auf Adresse 2D04 ausgegebenen Hexadezimalwert

ab Zeitpunkt in ns     Wert von LEDS
     0                  UU
   130                  01
   250                  02
   370                  03
   490                  04
   610                  05
   730                  06
   850                  07
   970                  08

Soll LEDS auf echte <a href="http://de.wikipedia.org/wiki/Leuchtdiode">LED</a>'s ausgegeben werden, muss natürlich der Takt CLK passend verringert werden.
</pr>

<weiter /><a href="R02_Stapelvariablen.xml">R02 Stapeleinträge benennen</a>
</los>

=== OpaStefanVogel/FORTY-FORTH/R12_Alles_Multi.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="R00.xsl" ?>
<!DOCTYPE los SYSTEM "R00.dtd">
<los>

<step>Step 8</step>

<pr>Alles Multi

Jetzt sollen mehrere Kopien des Prozessors gemeinsam eine Matrix invertieren. Zu diesem Zweck werden die Kopien ebenfalls in einer Matrix zusammengeschaltet. Jeder Prozessor erhält einen linken, rechten, oberen und unteren Nachbar. Am linken Rand zählt als linker Nachbar der Prozessor vom gegenüberliegenden rechten Rand in der gleichen Zeile, dementsprechend auch die Zuordnung an den anderen Rändern.

<object id="SVG_1" data="SVG_zu_R12.svg" width="550" height="260" />

Der Datenaustausch zwischen den einzelnen Prozessoren erfolgt über die Speicheradressen 7800H…7FFFH, gesteuert über die Adressen 2804H…2807H. <i>Weil sich so ziemlich alle Speicheradressen geändert haben, nochmal eine komplette Übersicht:</i>

Adresse     Bitbreite   Verwendung
<i>0000…1FFFH    16        Programmspeicher</i>
<i>2800H         16        Lesen und Bestätigen von KEYADR
2801H         16        Lesen und Setzen von SP
2802H         16        Lesen und Setzen von RP
2803H         16        Lesen und Setzen von PC</i>
2804H          1        RECHTS-ABGESCHICKT, LINKS-ABGESCHICKT
2805H          1        RECHTS-ANGEKOMMEN, LINKS-ANGEKOMMEN
2806H          1        UNTEN-ABGESCHICKT, OBEN-ABGESCHICKT
2807H          1        UNTEN-ANGEKOMMEN, OBEN-ANGEKOMMEN
<i>2C00…2FFFH    16        Rückkehrstapel und Variablen
3000…3FFFH     8        Textspeicher (nur Bytes)</i>
4000…5FFFH    16        Speicher für große Zahlen und Matrizen
7800…7BFFH    16        nach rechts schreiben, von links lesen
7C00…7FFFH    16        nach unten schreiben, von oben lesen

Jeder Prozessor kann im Adressbereich 7800H…7BFFH Daten zum rechts daneben befindlichen Prozessor schicken und mit 

<code>RECHTS-ANGEKOMMEN @ NOT RECHTS-ABGESCHICKT !</code>

mitteilen, dass die zu übertragenden Daten komplett in den Adressbereich 7800H…7BFFH gespeichert wurden. Der Prozessor rechts davon erkennt an der Änderung von LINKS-ABGESCHICKT, dass neue Daten vorliegen und signalisiert nach dem Auslesen und Auswerten mit 

<code>LINKS-ABGESCHICKT @ LINKS-ANGEKOMMEN !</code>

dass das Auslesen beendet ist und die nächsten Daten gesendet werden können. Entsprechendes gilt auch im Adressbereich 7800H-7FFFH für die Übertragungsrichtung von oben nach unten.

Zu beachten ist, was in 7800H…7FFFH gespeichert wird, kann (um unnötige Verbindungen zu vermeiden) nicht vom gleichen Prozessor zurückgelesen werden sondern nur vom Prozessor rechts oder unterhalb davon. Dieser wiederum kann diese Daten nur von 7800H…7FFFH auslesen und nicht durch Zurückspeichern vorher nochmal verändern. Entsprechende Schreibversuche gehen weiter an den nächsten rechten oder unteren Prozessor.
</pr>

<p>Im Beispielprogramm wird wieder die gleiche Matrix invertiert wie in Step_11. Allerdings werden die Matrixelemente einzeln mit <code>A(j,k)!</code> ein- und mit <code>B(j,k)@</code> ausgelesen, weil diese als komplette Matrix schnell eine Größe erreichen, für die der Speicher eines einzelnen Prozessors nicht mehr ausreicht.
</p>

<p>Neu bei der Simulation sind das Eingabefile <a href="test_input_file.txt">test_input_file.txt</a>, das Ausgabefile <a href="test_output_file.txt">test_output_file.txt</a> und zusätzliche Ausgabe in der TCL Console. Dadurch wird ermöglicht, <i>vivado</i> auch ohne grafische Oberfläche (GUI) im Modus <i>vivado -mode tcl</i> laufen zu lassen, wenn nur die simulierte Programmausgabe als Ergebnis benötigt wird.</p>
 
<Terminal_1>
  <li> git checkout Step_12 </li>
  <li> git diff Step_12...Step_11 </li>
  </Terminal_1>

<Tcl_Console>
  <li> close_sim -force -quiet </li>
  <li> source <a>RamINIT.tcl</a> # RAM neu initialisieren </li>
  <li> launch_simulation </li>
  <li> run 200 ms </li>
  </Tcl_Console>

<DEMO>FORTY-FORTH

ok
<u>HEX</u> ok
<u>HERE . BZEIG M?</u> 1B5D 3AF4 ok
<u>0 0 JK-PROC</u> ok
<u>NJ M? NK M?</u> 2 2 ok
<u>0 2D04 ! 0 ACBIT ! 0 ADBIT !</u> ok
<u></u> ok
<u>DECIMAL</u> ok
<u>AUSGANGSMATRIX_NULLSETZEN</u> ok
<u>1 0 0 A(j,k)!  1 0 1 A(j,k)!  1 0 2 A(j,k)!   1 0 3 A(j,k)! </u> ok
<u>2 1 0 A(j,k)!  4 1 1 A(j,k)!  8 1 2 A(j,k)!  16 1 3 A(j,k)! </u> ok
<u>3 2 0 A(j,k)!  9 2 1 A(j,k)! 27 2 2 A(j,k)!  81 2 3 A(j,k)! </u> ok
<u>4 3 0 A(j,k)! 16 3 1 A(j,k)! 64 3 2 A(j,k)! 256 3 3 A(j,k)! </u> ok
<u>1 HAUPTNENNER</u> ok
<u></u> ok
<u>4 N ! INVERTIERE_SCHNELL</u> ok
<u></u> ok
<u>0 0 B(j,k)@ .</u> 1152 ok
<u>0 1 B(j,k)@ .</u> -864 ok
<u>0 2 B(j,k)@ .</u> 384 ok
<u>0 3 B(j,k)@ .</u> -72 ok
<u>1 0 B(j,k)@ .</u> -1248 ok
<u>1 1 B(j,k)@ .</u> 1368 ok
<u>1 2 B(j,k)@ .</u> -672 ok
<u>1 3 B(j,k)@ .</u> 132 ok
<u>2 0 B(j,k)@ .</u> 432 ok
<u>2 1 B(j,k)@ .</u> -576 ok
<u>2 2 B(j,k)@ .</u> 336 ok
<u>2 3 B(j,k)@ .</u> -72 ok
<u>3 0 B(j,k)@ .</u> -48 ok
<u>3 1 B(j,k)@ .</u> 72 ok
<u>3 2 B(j,k)@ .</u> -48 ok
<u>3 3 B(j,k)@ .</u> 12 ok
<u>DUP .</u> 288 ok
</DEMO>

<svg_path schnips="1 1 -3 -100"/>
</los>

=== OpaStefanVogel/FORTY-FORTH/R09_Programmausgabe.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="R00.xsl" ?>
<!DOCTYPE los SYSTEM "R00.dtd">
<los>

<step>Step 9</step>

<pr>Programmausgabe

Variablen:
EMIT_BYTE        = enthält das auszugebende Byte
EMIT_ABGESCHICKT = wird invertiert, wenn ein Byte gesendet wurde,
EMIT_ANGEKOMMEN  = muss vom Empfänger invertiert werden. Das Programm wartet solange mit dem Absenden des nächsten Bytes.

EMIT  ( n --> ) gibt n auf Port EMIT_BYTE aus.

Ein Beispielprogramm wie</pr>
<ptable>
  <tr><td> 0000 </td><td> 0031 </td><td> 54 ( '1' )</td><td> 31    </td><td> 1 </td></tr>
  <tr><td> 0001 </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  <tr><td> 0002 </td><td> 002E </td><td> 45 ( '.' )</td><td> 2E    </td><td> 1 </td></tr>
  <tr><td> 0003 </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  <tr><td> 0004 </td><td> 0020 </td><td> 53 ( ' ' )</td><td> 20    </td><td> 1 </td></tr>
  <tr><td> 0005 </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  <tr><td> 0006 </td><td> 0054 </td><td> 54 ( 'T' )</td><td> 54    </td><td> 1 </td></tr>
  <tr><td> 0007 </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  <tr><td> 0008 </td><td> 0054 </td><td> 45 ( 'E' )</td><td> 45    </td><td> 1 </td></tr>
  <tr><td> 0009 </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  <tr><td> 000A </td><td> 0054 </td><td> 53 ( 'S' )</td><td> 53    </td><td> 1 </td></tr>
  <tr><td> 000B </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  <tr><td> 000C </td><td> 0054 </td><td> 54 ( 'T' )</td><td> 54    </td><td> 1 </td></tr>
  <tr><td> 000D </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  <tr><td> 000E </td><td> 0054 </td><td> 20 ( ' ' )</td><td> 20    </td><td> 1 </td></tr>
  <tr><td> 000F </td><td> A005 </td><td> EMIT      </td><td>       </td><td> 0 </td></tr>
  </ptable>
  
<p>ist inzwischen etwas dürftig. Ich habe deshalb einen ersten FORTH-Interpreter in ProgRAM (ab PC=0010) und ByteRAM gepackt. Eine Minimalversion, die sich gerade so selbst zum Laufen bringt, mal sehen, ob da schon was gescheites passiert.</p>

<Terminal_1>
  <li> git checkout Step_9 </li>
  <li> git diff <diff>Step_8...Step_9</diff> </li>
  </Terminal_1>

<Tcl_Console>
  <li> close_sim -force -quiet </li>
  <li> launch_simulation </li>
  <li> run 20000 ns </li>
  </Tcl_Console>

<p>Beginnend ab 380 ns wird alle 820 ns auf EMIT ein weiteres Zeichen der Hexadezimalfolge 46-4F-52-54-59-2d-46-4f-52-54-48-0A-0A-6F-6B-0A ausgegeben. In einem echten Terminal würde das etwa so aussehen:</p>

<DEMO>FORTY-FORTH

ok
</DEMO>

<p>Von 900 ns bis 1220 ns wartet der Programmzähler PC darauf, dass von testbench.vhd aus EMIT_EMPFANGEN negiert wird, und so auch bei jedem weiteren ausgegebenen Zeichen. Schließlich ab 15540 ns wiederholt sich endlos eine 420 ns lange Progammschleife - ja weil noch eine Nutzereingabe fehlt...</p>

<weiter /><a href="R10_Nutzereingabe.xml">R10 Nutzereingabe</a>

</los>

=== OpaStefanVogel/FORTY-FORTH/R11_ganze_Zahlen.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="R00.xsl" ?>
<!DOCTYPE los SYSTEM "R00.dtd">
<los>

<step>Step 11</step>

<pr>Große ganze Zahlen

Zum Rechnen mit großen ganzen Zahlen sind weitere Rechenoperationen eingefügt, welche den Rechenablauf beschleunigen sollen.

DI32 ( a b c --> r q ) teilt die aus a und b zusammengesetzte 32-Bit Zahl a*2^16+b durch c und gibt Rest r und Quotient q zurück.
MULT_I ( ... ) und
MULT_II ( ... ) sind zwei Hilfsfunktionen für die Multiplikation einer 16-Bit-Zahl mit einer ab Adresse adr gespeicherten großen ganzen Zahl der Länge l Bytes.

Hier ist nur aufgeführt, was im VHDL-Programm dazugekommen ist. Wie das alles mit dem FORTH-Interpreter zusammenwirkt und daraus schließlich das Matrix-Invertierungsprogramm gemacht wird, öffne dazu die Datei <a href="screenlog.xml">screenlog.xml</a>. Das ist ein Logfile, welches beim Compilieren des Forth-Interpreters angefertigt wurde. Es enthält den vollständigen FORTH-Quelltext, versehen mit wenigstens ein paar Erläuterungen.

Beispielaufgabe: <i>Invertiere die Matrix

  [ [ 1   1   1    1 ] 
    [ 2   4   8   16 ] 
    [ 3   9  27   81 ]
    [ 4  16  64  256 ] ] </i></pr>

<Terminal_1>
  <li> git checkout Step_11 </li>
  <li> git diff Step_10...Step_11 </li>
  </Terminal_1>

<Tcl_Console>
  <li> close_sim -force -quiet </li>
  <li> launch_simulation </li>
  <li> run 60 ms </li>
  </Tcl_Console>

<p></p>

<DEMO>FORTY-FORTH

ok
<u>56 89 * .</u> 2E06 ok
<u>111111111111111 DUP * .</u> 123456789ABCDEFEDCBA987654321 ok
<u>DECIMAL</u> ok
<u>56 89 * .</u> 4984 ok
<u>[ [ 1   1   1    1 ]</u> ok
<u>  [ 2   4   8   16 ]</u> ok
<u>  [ 3   9  27   81 ]</u> ok
<u>  [ 4  16  64  256 ] ] </u> ok
<u>4 INVERTIEREN</u> 
<u>OVER .</u> [ [ 1152 -864 384 -72 ] [ -1248 1368 -672 132 ] [ 432 -576 336 -72 ] [ -48 72 -48 12 ] ] ok
<u>DUP .</u> 288 ok
</DEMO>

<p>Die Nutzereingaben <u>56 89 * ....</u> beginnen ab 30000 ns in KEY_BYTE. Die Ergebnisse werden jeweils ab 3826300 ns, ab 7552740 ns, ab 11061760 ns auf EMIT_BYTE ausgegeben. Darin enthaltene ESCAPE-Sequenzen wie 1B-5B-33-36-6D (ESC-[-3-6-m) stellen die Schriftfarbe ein. DECIMAL schaltet auf dezimale Zahlenbasis um. INVERTIEREN holt vom Stapel die Matrix [ [ 1 ... ] ] und die Dimension 4 und gibt deren Inverse [ [ 1152 ... ] ] und den gemeinsamen Nenner 288 aller Matrixelemente auf dem Stapel zurück (ab 55243300 ns).</p>  

<weiter /><a href="Spartan3.xml">Installation Spartan3 Board</a>

<svg_path schnips="1 1 -50 -87"/>
</los>

=== OpaStefanVogel/FORTY-FORTH/Spartan3.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="R00.xsl" ?>
<!DOCTYPE los SYSTEM "R00.dtd">
<los>

<step>Spartan3</step>

<pr>Spartan3

Letzter Schritt war branch <code>Step_10</code> in Terminal-1. Alle für das Spartan3 Board benötigt Dateien befinden sich in einem extra Branch, welcher nicht gleichzeitig mit in Terminal-1 eingestellt werden kann. Deshalb in einem neuen Terminal-2 ein neues leeres Verzeichnis mit einem selbstgewählten Namen <i>your-Spartan3-repo</i> anlegen, in dieses Verzeichnis wechseln und nochmal klonen.</pr>

<sterm>git clone https://github.com/OpaStefanVogel/FORTY-FORTH.git .
git checkout Spartan3_Step_9_und_10</sterm>

<pr>Die Ein- und Ausgabe soll über die serielle Verbindung zum Spartan3 Board erfolgen. Dafür wird ein weiteres Terminal-3 benötigt. Welches Verzeichnis darin eigestellt ist, ist dafür egal. Jedoch kann anstelle <code>/ttyS0</code> auch <code>/ttyS1</code> oder eine andere Eingabe erforderlich sein.</pr>

<yterm>stty -F /dev/ttyS0 115200 raw -cstopb -parenb -crtscts -echo ixon -ixoff
stty raw -echo opost quit ^C isig ixon -ixoff #hiernach ist es finster!!!
cp /dev/ttyS0 /dev/tty &amp; cp /dev/tty /dev/ttyS0
</yterm>

<pr>(alles mit Enter abschließen, man sieht nach dem zweiten stty keine Bildschirmausgabe mehr, in dem Moment ist noch nicht erkennbar, ob es funktioniert)

So, jetzt muss mit <a href="https://en.wikipedia.org/wiki/Xilinx_ISE">Xilinx_ISE</a> ein Projekt mit den Dateien

<i>your-master-repo</i>/P01_top.vhd
<i>your-master-repo</i>/P20_FFP.vhd
<i>your-Spartan3-repo</i>/TopSpartan3.vhd
<i>your-Spartan3-repo</i>/Platine95S3.ucf

angelegt werden, das .bit File generiert und auf den Spartan3 ausgegeben werden. Dann sollte in Terminal-3 wieder</pr>

<ffterm>FORTY-FORTH

ok</ffterm>

<pr>zu sehen sein. Wenn nicht, erstmal mit Eingabe von Enter und ESCAPE versuchen, ob sich da nur was verheddert hat. Sonst bleibt nur, in Terminal 1 und 2 mit <code>git checkout</code> auf vorherige Versionen umzuschalten, .bit erneut zu generieren und auf den Spartan3 auszugeben. Dabei gilt momentan folgende Zuordnung</pr>

<table border="1">
  <tr><th><i>your-master-repo&amp;</i></th><th><i>your-Spartan3-repo&amp;</i></th><th>Ausgabe</th></tr>
  <tr><td>Step_1</td><td>Spartan_Step_1_bis_5_und_8</td><td>LED's</td></tr>
  <tr><td>Step_2</td><td>Spartan_Step_1_bis_5_und_8</td><td>LED's</td></tr>
  <tr><td>Step_3</td><td>Spartan_Step_1_bis_5_und_8</td><td>LED's</td></tr>
  <tr><td>Step_4</td><td>Spartan_Step_1_bis_5_und_8</td><td>LED's</td></tr>
  <tr><td>Step_5</td><td>Spartan_Step_1_bis_5_und_8</td><td>LED's</td></tr>
  <tr><td>Step_6</td><td>Spartan_Step_6_und_7</td><td>LED's</td></tr>
  <tr><td>Step_7</td><td>Spartan_Step_6_und_7</td><td>LED's</td></tr>
  <tr><td>Step_8</td><td>Spartan_Step_1_bis_5_und_8</td><td>LED's</td></tr>
  <tr><td>Step_9</td><td>Spartan_Step_9_und_10</td><td>serieller Ausgang</td></tr>
  <tr><td>Step_10</td><td>Spartan_Step_9_und_10</td><td>serieller Ausgang</td></tr>
  </table>
  
<pr>Anstelle oder nach einigen Tastatureingaben in Terminal-3 hinein geht auch in Terminal-1</pr>

<term>cp FFINIT1.TXT /dev/ttyS0 # recompiliert den vorhandenen FORTH-Interpreter 
cp FFINIT2.TXT /dev/ttyS0 # erste Erweiterungen
cp DEMO.TXT /dev/ttyS0 # DEMO-File</term><weiter />Pause
</los>
